openapi: "3.1.0"
info:
  title: User Service API
  version: "1.0.0"

servers:
  - url: https://api.example.com
    description: Production server
  - url: http://localhost:8080
    description: Local development server

security:
  - bearerAuth: []

paths:
  /auth/register:
    $ref: './paths/auth/register.yaml'
  /auth/login:
    $ref: './paths/auth/login.yaml'
  /auth/logout:
    $ref: './paths/auth/logout.yaml'
  /auth/validate:
    $ref: './paths/auth/validate.yaml'
  /auth/refresh:
    $ref: './paths/auth/refresh.yaml'


components:
  schemas:
    RegisterRequest:
      $ref: './components/schemas/RegisterRequest.yaml'
    LoginRequest:
      $ref: './components/schemas/LoginRequest.yaml'
    LogoutRequest:
      $ref: './components/schemas/LogoutRequest.yaml'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
