name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  docker-build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: frontend
            context: ./frontend
          - name: bff
            context: ./bff
          # TODO: バックエンドサービス追加
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # TODO: configure all services
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Build and push ${{ matrix.service.name }} Docker image
      #   uses: ./.github/actions/docker-build-push
      #   with:
      #     context: ${{ matrix.service.context }}
      #     image-name: ${{ matrix.service.name }}
