name: Lint

on:
  push:
    branches-ignore: [ main ]

jobs:
  typescript-lint:
    name: TypeScript Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, bff]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js and PNPM
        uses: ./.github/actions/setup-node
      
      - name: Install dependencies
        working-directory: ./${{ matrix.service }}
        run: pnpm install
      
      - name: Lint
        working-directory: ./${{ matrix.service }}
        run: pnpm lint
      
      - name: Format
        working-directory: ./${{ matrix.service }}
        run: pnpm format
  
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
          service: [project, user, session, board, column, role, tag, task]
          include:
            - service: project
              path: backend/project
            - service: user
              path: backend/user
            - service: session
              path: backend/session
            - service: board
              path: backend/board
            - service: column
              path: backend/column
            - service: role
              path: backend/role
            - service: tag
              path: backend/tag
            - service: task
              path: backend/task
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: ${{ matrix.path }}/go.sum

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: ${{ matrix.path }}
      
      # TODO: add format check
      # - name: Install golangci-lint
      #   run: |
      #     go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.5
      
      # - name: Run lint and format check
      #   working-directory: ${{ matrix.path }}
      #   run: |
      #     golangci-lint run ./...
      #     golangci-lint fmt --check ./...